# scripts/git_sync.py
"""
GitHub 자동 동기화
"""
import subprocess
import os
from datetime import datetime
from pathlib import Path

def sync_to_github(nft_data):
    """
    NFT 데이터를 GitHub에 자동 커밋 및 푸시

    Args:
        nft_data: {
            "index": 1,
            "title": "제목",
            "image_path": "output/images/nft_001.png",
            "landing_url": "...",
            ...
        }
    """
    try:
        print("📦 Syncing to GitHub...")

        # 이미지 파일을 public/images로 복사
        import shutil
        image_filename = Path(nft_data["image_path"]).name
        dest_path = Path(f"public/images/{image_filename}")
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(nft_data["image_path"], dest_path)

        # Git 명령어 실행
        commands = [
            "git add public/",
            "git add output/metadata/",
            f'git commit -m "🎨 New NFT #{nft_data["index"]:03d}: {nft_data["title"]}\n\n🤖 Auto-generated by N100 Mini PC\n💎 Style: {nft_data["style"]}\n⏰ {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}"',
            "git push origin main"
        ]

        for cmd in commands:
            result = subprocess.run(
                cmd,
                shell=True,
                capture_output=True,
                text=True
            )

            if result.returncode != 0:
                # commit에 변경사항이 없을 때는 에러가 아님
                if "nothing to commit" in result.stdout or "nothing to commit" in result.stderr:
                    print("ℹ️  No changes to commit")
                    continue
                else:
                    print(f"⚠️  Git command warning: {result.stderr}")

        print("✅ Synced to GitHub")

    except Exception as e:
        print(f"❌ GitHub sync failed: {str(e)}")


def setup_git_repo():
    """
    Git 저장소 초기 설정 (최초 1회 실행)
    """
    commands = [
        "git init",
        "git branch -M main",
        f'git remote add origin https://github.com/{os.getenv("GITHUB_REPO")}.git'
    ]

    for cmd in commands:
        subprocess.run(cmd, shell=True)

    print("✅ Git repository initialized")


if __name__ == "__main__":
    # 테스트
    test_data = {
        "index": 999,
        "title": "Test NFT",
        "image_path": "output/images/nft_999.png",
        "style": "realistic"
    }
    # sync_to_github(test_data)
    print("Git sync ready!")
